# Generated by Django 5.2.4 on 2025-08-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(help_text='Employee ID should be unique (e.g., EMP1234)', max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('Finance', 'Finance'), ('Operations', 'Operations')], max_length=20)),
                ('location', models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad')], max_length=20)),
                ('terms_agreed', models.BooleanField(default=False)),
            ],
        ),
    ]
