# Generated by Django 5.2.4 on 2025-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_category', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('accessory', 'Accessory'), ('other', 'Other')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=100)),
                ('warranty_period', models.CharField(choices=[('6months', '6 Months'), ('1year', '1 Year'), ('2years', '2 Years'), ('3years', '3+ Years')], max_length=10)),
                ('assigned_department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Operations', 'Operations'), ('Engineering', 'Engineering'), ('ATM', 'ATM'), ('Commercial', 'Commercial'), ('Finance', 'Finance'), ('Marketing', 'Marketing')], max_length=20)),
                ('asset_photo', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('initial_status', models.CharField(choices=[('in-stock', 'In Stock'), ('in-use', 'In Use')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
