# Generated by Django 5.2.4 on 2025-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('Air Traffic Control', 'Air Traffic Control'), ('Engineering', 'Engineering'), ('Security', 'Security'), ('Administration', 'Administration'), ('IT Services', 'IT Services'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=30)),
                ('related_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical - System Down'), ('high', 'High - Major Impact'), ('medium', 'Medium - Partial Functionality'), ('low', 'Low - General Inquiry')], max_length=10)),
                ('issue_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network'), ('Access/Permissions', 'Access/Permissions'), ('Email', 'Email'), ('Other', 'Other')], max_length=20)),
                ('issue_description', models.TextField()),
                ('urgent', models.BooleanField(default=False)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
